const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.bound,
		C3.Behaviors.Flash,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Particles,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Sin,
		C3.Behaviors.destroy,
		C3.Plugins.TiledBg,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.JavaScriptInEvents.FolhaDeEventos1_Event2_Act6,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Flash.Cnds.OnFlashEnded,
		C3.Plugins.TiledBg.Cnds.CompareY
	];
};
self.C3_JsPropNameTable = [
	{xVelocidade: 0},
	{yVelocidade: 0},
	{RestritoAoLayout: 0},
	{Piscar: 0},
	{Jogador: 0},
	{Tiro: 0},
	{Vida1: 0},
	{Inimigo: 0},
	{Mouse: 0},
	{Teclado: 0},
	{Explosão: 0},
	{Pontuação: 0},
	{Senóide: 0},
	{PoderEscudo: 0},
	{DestruirForaDoLayout: 0},
	{Escudo: 0},
	{VidaX: 0},
	{VidaIcon: 0},
	{VidaPlayer: 0},
	{Fundo: 0},
	{Vida3: 0},
	{Inimigo3: 0},
	{Vida2: 0},
	{Inimigo2: 0},
	{PoderVida: 0},
	{Áudio: 0},
	{SeLascou: 0}
];

self.InstanceType = {
	Jogador: class extends self.ISpriteInstance {},
	Tiro: class extends self.ISpriteInstance {},
	Inimigo: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Teclado: class extends self.IInstance {},
	Explosão: class extends self.IParticlesInstance {},
	Pontuação: class extends self.ISpriteFontInstance {},
	PoderEscudo: class extends self.ISpriteInstance {},
	Escudo: class extends self.ISpriteInstance {},
	VidaX: class extends self.ISpriteInstance {},
	VidaIcon: class extends self.ISpriteInstance {},
	VidaPlayer: class extends self.ISpriteFontInstance {},
	Fundo: class extends self.ITiledBackgroundInstance {},
	Inimigo3: class extends self.ISpriteInstance {},
	Inimigo2: class extends self.ISpriteInstance {},
	PoderVida: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {}
}